Tests
Khaled-Alaa-1/Math-magicians pull request #6
Opened 2023-07-13 23:02 UTC by Khaled-Alaa-1

### In this project we :

- Use React Router.
- Add root pages
   -Use styles in a React app.

2023-07-13 23:25 UTC, DuaneDave requested changes
Hi @Khaled-Alaa-1 and @PedroH-Neves 👋 , 

Good job so far on this project!
There are some issues that you still need to work on to go to the next project but you are almost there!

## Highlights
✔️ Correct usage of git-flow
✔️ Good usage of react testing library

## Required Changes ♻️
_Check the comments under the review._

## Optional suggestions
N/A

_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-07-13 23:25 UTC, DuaneDave commented on src/logic/operate.test.js
> +});
According to the requirements, tests that cover all scenarios of the operate js should be written and I recommend writing more tests to see if other functions are working as expected.

2023-07-13 23:25 UTC, DuaneDave commented on src/logic/calculate.test.js
> +});
According to the requirements, tests that cover all scenarios of the calculate js should be written and I recommend writing more tests to see if other functions are working as expected.

2023-07-14 07:42 UTC, danmainah approved these changes
Hi @Khaled-Alaa-1 , 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 🎉 🎉 

## Highlights
✔️  Implemented requested changes to ensure all tests scenario are covered and all tests are passing.

## Optional suggestions

- [x] Great work implementing all changes requested I would recommend you add tests for all components.

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-07-14 16:27 UTC, merged